In [1]:
import arcpy
from arcpy import env
import pandas as pd

In [2]:
env.workspace = r"T:\DCProjects\DataPortal\Data\LODES\LODES.gdb"
env.overwriteOutput = True

In [3]:
tabblock10 = r"T:\DCProjects\DataPortal\Data\tabblock2010_41_pophu\tabblock2010_41_pophu.shp"

In [4]:
city = r"T:\DCProjects\DataPortal\Data\city\city.shp"

In [5]:
cities = pd.read_csv(r"T:\DCProjects\DataPortal\Data\Output\or_city_coordinates.csv")

In [6]:
cities.head()

            City                   Place   Latitude   Longitude
0  Adair Village  Adair Village city, OR  44.673529 -123.216959
1          Adams          Adams city, OR  45.767510 -118.564254
2         Adrian         Adrian city, OR  43.740351 -117.070510
3         Albany         Albany city, OR  44.630080 -123.093637
4          Amity          Amity city, OR  45.116107 -123.204701

In [7]:
list(cities['City'].unique())[1:5]

['Adams', 'Adrian', 'Albany', 'Amity']

In [8]:
def get_blockIDs(citynm):
    # require city and block data
    print(citynm)
    selected_city = arcpy.management.SelectLayerByAttribute(city, "NEW_SELECTION", "FIRST_NAME = '{0}'".format(citynm), None)
    selected_blocks = arcpy.management.SelectLayerByLocation(tabblock10, "HAVE_THEIR_CENTER_IN", selected_city, None, "NEW_SELECTION", "NOT_INVERT")
    layer_object = selected_blocks.getOutput(0)
    blockIDs = [row[0] for row in   arcpy.da.SearchCursor(layer_object, "BLOCKID10")]
    return(blockIDs)

In [10]:
blockIDs = get_blockIDs(citynm = 'Adams')

Adams

In [11]:
cities['BlockIDs'] = cities.City.apply(lambda x: get_blockIDs(x))

Adair Village
Adams
Adrian
Albany
Amity
Antelope
Arlington
Ashland
Astoria
Athena
Aumsville
Aurora
Baker City
Bandon
Banks
Barlow
Bay City
Beaverton
Bend
Boardman
Brookings
Brownsville
Burns
Canby
Cannon Beach
Canyonville
Carlton
Cascade Locks
Cave Junction
Central Point
Chiloquin
Clatskanie
Coburg
Columbia City
Condon
Coos Bay
Coquille
Cornelius
Corvallis
Cottage Grove
Cove
Creswell
Culver
Dallas
Damascus
Dayton
Depoe Bay
Detroit
Donald
Drain
Dufur
Dundee
Dunes City
Durham
Eagle Point
Echo
Elgin
Elkton
Enterprise
Estacada
Eugene
Fairview
Falls City
Florence
Forest Grove
Fossil
Garibaldi
Gaston
Gates
Gearhart
Gervais
Gladstone
Glendale
Gold Beach
Gold Hill
Grants Pass
Grass Valley
Gresham
Haines
Halfway
Halsey
Happy Valley
Harrisburg
Helix
Heppner
Hermiston
Hillsboro
Hines
Hood River
Hubbard
Huntington
Idanha
Imbler
Independence
Ione
Irrigon
Island City
Jacksonville
Jefferson
John Day
Johnson City
Jordan Valley
Joseph
Junction City
Keizer
King City
Klamath Falls
La Grande
La Pine
Lafayette
Lake Oswego
Lakeside
Lebanon
Lincoln City
Lonerock
Long Creek
Lostine
Lowell
Lyons
Madras
Malin
Manzanita
Maupin
Maywood Park
McMinnville
Medford
Merrill
Metolius
Mill City
Millersburg
Milton-Freewater
Milwaukie
Mitchell
Molalla
Monmouth
Monroe
Monument
Moro
Mosier
Mount Angel
Mount Vernon
Myrtle Creek
Myrtle Point
Nehalem
Newberg
Newport
North Bend
North Plains
North Powder
Nyssa
Oakland
Oakridge
Ontario
Oregon City
Paisley
Pendleton
Philomath
Phoenix
Pilot Rock
Port Orford
Portland
Powers
Prairie City
Prineville
Rainier
Redmond
Reedsport
Richland
Riddle
Rivergrove
Rockaway Beach
Rogue River
Roseburg
Rufus
Salem
Sandy
Scappoose
Scio
Scotts Mills
Seaside
Seneca
Shady Cove
Sheridan
Sherwood
Siletz
Silverton
Sisters
Sodaville
Springfield
St. Helens
St. Paul
Stanfield
Stayton
Sublimity
Sumpter
Sutherlin
Sweet Home
Talent
Tangent
The Dalles
Tigard
Tillamook
Toledo
Troutdale
Tualatin
Turner
Ukiah
Umatilla
Union
Unity
Vale
Veneta
Vernonia
Waldport
Wallowa
Warrenton
Wasco
West Linn
Weston
Wheeler
Willamina
Wilsonville
Winston
Wood Village
Woodburn
Yachats
Yamhill
Yoncalla
Granite
Westfir
Shaniko
Prescott

In [12]:
cities.head()

,City,Place,Latitude,Longitude,BlockIDs
0,Adair Village,"Adair Village city, OR",44.673529,-123.216959,"[410030102001158, 410030102001177, 41003010200..."
1,Adams,"Adams city, OR",45.767510,-118.564254,"[410599503003070, 410599503003081, 41059950300..."
2,Adrian,"Adrian city, OR",43.740351,-117.070510,"[410459707001248, 410459707001247, 41045970700..."
3,Albany,"Albany city, OR",44.630080,-123.093637,"[410030101005012, 410030101003007, 41003010100..."
4,Amity,"Amity city, OR",45.116107,-123.204701,"[410710310002058, 410710310002061, 41071031000..."

In [13]:
cities.to_csv(r"T:\DCProjects\DataPortal\Data\Output\or_city_blockIDs.csv", index = False)